services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pharmacy_backend_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - pharmacy-network
    environment:
      - PHP_FPM_LISTEN=0.0.0.0:9000

  nginx:
    image: nginx:alpine
    container_name: pharmacy_backend_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pharmacy-network
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: pharmacy_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: pharmacy_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: pharmacy_user
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - pharmacy-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  pharmacy-network:
    name: pharmacy-network
    external: false

volumes:
  dbdata:
    driver: local

